version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "18001:9000"
      - "18002:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 12345678
    volumes:
      - ./pkg/minio/data:/data
      - ./pkg/minio/configs:/root/.minio
    command: server --console-address ':9001' /data
    privileged: true
    restart: always
    profiles:
      - dev
      - release