// Code generated by hertz generator.

package favorite

import (
	"context"
	favorite "douyin/biz/model/interact/favorite"
	"douyin/biz/mw/jwt"
	service "douyin/biz/service/favorite"
	"douyin/pkg/errno"
	"douyin/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FavoriteAction .
// @router /douyin/favorite/action/ [POST]
func FavoriteAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.DouyinFavoriteActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, favorite.DouyinFavoriteActionResponse{
			StatusCode: resp.StatusCode,
			StatusMsg:  resp.StatusMsg,
		})
		return
	}

	jwt.MW.LoginHandler(ctx, c)
	ok, err := service.NewFavoriteService(ctx, c).FavoriteAction(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, favorite.DouyinFavoriteActionResponse{
			StatusCode: resp.StatusCode,
			StatusMsg:  resp.StatusMsg,
		})
		return
	}

	if !ok {
		resp := utils.BuildBaseResp(errno.FavoriteActionErr)
		c.JSON(consts.StatusOK, favorite.DouyinFavoriteActionResponse{
			StatusCode: resp.StatusCode,
			StatusMsg:  resp.StatusMsg,
		})
		return
	}

	c.JSON(consts.StatusOK, favorite.DouyinFavoriteActionResponse{
		StatusCode: errno.SuccessCode,
		StatusMsg:  errno.SuccessMsg,
	})
}

// FavoriteList .
// @router /douyin/favorite/list/ [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.DouyinFavoriteListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	favoriteList, err := service.NewFavoriteService(ctx, c).GetFavoriteList(&req)
	if err != nil {
		utils.BuildBaseResp(err)
		return
	}
	resp := favorite.DouyinFavoriteListResponse{
		VideoList:  favoriteList,
		StatusCode: errno.SuccessCode,
		StatusMsg:  errno.SuccessMsg,
	}
	c.JSON(consts.StatusOK, resp)
}
